"""A dog restricted to named people stays restricted after a restart, however it is started.

Two paths start a dog at logon: the launcher `collie slack --install-autostart` writes, and the
supervisor, which copies that launcher's command line into supervisor.json. The launcher dropped
`--allow`, and the supervisor's copy was taken once and never followed a re-installed launcher, so
the developer machine's supervised dog was answering "anyone in them" while its launcher said
`--allow U0BMGMUPUQ6`. Nothing here starts a dog or touches a real Startup folder.
"""
import json
import os

from harness import plat, slackbot as sb, supervisor


class _WP:
    def _pkg_parent(self):
        return "/site-packages"

    def pythonw(self):
        return "/pythonw.exe"


def test_the_windows_launcher_keeps_who_may_command_the_dog(tmp_path, monkeypatch):
    boot, vbs = tmp_path / "slack-rowan.pyw", tmp_path / "collie-slack-rowan.vbs"
    monkeypatch.setattr(sb, "_autostart_paths", lambda name: (_WP(), str(boot), str(vbs)))
    monkeypatch.setattr(plat, "is_windows", lambda: True)
    assert sb.install_autostart("rowan", "/repo", channels="C1", allow="U1,U2",
                                autonomy="branch") == 0
    argv = supervisor._legacy_slack_argv(str(tmp_path))
    assert argv == [["slack", "--name", "rowan", "--cwd", "/repo", "--channels", "C1",
                     "--allow", "U1,U2", "--autonomy", "branch"]]


def test_the_macos_launch_agent_keeps_who_may_command_the_dog(tmp_path, monkeypatch):
    written = {}
    monkeypatch.setattr(sb, "_agent_path", lambda name: str(tmp_path / "agent.plist"))
    monkeypatch.setattr(sb, "_plist", lambda label, argv, cwd, log: written.setdefault("argv", argv) and "")
    monkeypatch.setattr(sb.subprocess, "run", lambda *a, **k: type("R", (), {"returncode": 0,
                                                                             "stdout": "", "stderr": ""})())
    monkeypatch.setattr(os, "getuid", lambda: 501, raising=False)
    sb._install_launch_agent("rowan", "/repo", channels="C1", allow="U1")
    argv = written["argv"]
    assert argv[argv.index("--allow") + 1] == "U1"


def test_the_supervised_dog_follows_its_reinstalled_launcher(tmp_path):
    launcher = tmp_path / "slack-rowan.pyw"
    launcher.write_text("# auto-generated by `collie slack --install-autostart`.\n"
                        "sys.argv = ['collie'] + ['slack', '--name', 'rowan', '--cwd', '/repo', "
                        "'--channels', 'C1', '--allow', 'U1', '--autonomy', 'branch']\n",
                        encoding="utf-8")
    stale = supervisor.default_config(str(tmp_path), "/py")
    for worker in stale["workers"]:
        if worker["name"] == "slack-rowan":
            # What supervisor.json held from before the launcher gained --allow, plus a
            # person's own edit to another field, which must survive.
            worker["argv"] = ["/py", "-m", "harness.cli", "slack", "--name", "rowan", "--cwd",
                              "/repo", "--channels", "C1"]
            worker["startup_grace_s"] = 45
    (tmp_path / "supervisor.json").write_text(json.dumps(stale), encoding="utf-8")
    loaded = supervisor.load_config(str(tmp_path / "supervisor.json"), python="/py")
    dog = next(w for w in loaded["workers"] if w["name"] == "slack-rowan")
    assert dog["argv"][dog["argv"].index("--allow") + 1] == "U1"
    assert "--autonomy" in dog["argv"]
    assert dog["startup_grace_s"] == 45


def test_a_dog_without_a_launcher_is_left_exactly_as_configured(tmp_path):
    config = supervisor.default_config(str(tmp_path), "/py")
    config["workers"].append(supervisor.WorkerSpec(
        "slack-hand", ["/py", "-m", "harness.cli", "slack", "--name", "hand"]).as_dict())
    (tmp_path / "supervisor.json").write_text(json.dumps(config), encoding="utf-8")
    loaded = supervisor.load_config(str(tmp_path / "supervisor.json"), python="/py")
    dog = next(w for w in loaded["workers"] if w["name"] == "slack-hand")
    assert dog["argv"] == ["/py", "-m", "harness.cli", "slack", "--name", "hand"]
